stages:
  - compile
  - test

build:
  stage: compile
  image: golang:latest
  script:
    - go get -d -v
    - go build -o bin/gintoki -v .
test:
  stage: test
  image: golang:latest
    - go test -v ./...
